name: Go

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  generation:
    name: Generation
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go mod download

      - name: Generating files
        run: go generate ./...

      - uses: setare/git-changes-action@v0.1.4
        with:
          github_token: ${{ github.token }}
          name: 'File generation check'

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - generation
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          go mod download

      - name: Lint
        run: |
          make lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs:
      - generation
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          go mod download

      - name: Unit tests
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out

  integration-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    needs:
      - generation
      - unit-tests
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          go mod download

      - name: Unit tests
        run: |
          go test ./... -v -tags=integration
